### ISSUE TITLE
Regarding Dataset

### ISSUE THREAD

**Issue by agshubhs** [amilworks/GanDetection#1]
Hi @amilworks
Can you please specify which dataset you have used and how I can pre process it for the running the code.

**Comment by drprajapati** [comment]
> Hi @amilworks
> Can you please specify which dataset you have used and how I can pre process it for the running the code.

He used the LSUN or CelebA Dataset

**Comment by amilworks** [comment]
This is correct `LSUN, CelebA Dataset`, thanks for using the repo!
